package com.example.homebankfront.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val primaryDark = Color(0xFF1B1B1B)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF1B1B1B)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val inversePrimaryDark = Color(0xFF1B1B1B)
val secondaryDark = Color(0xFF2B2B2B)
val onSecondaryDark = Color(0xFF808080)
val secondaryContainerDark = Color(0xFF2B2B2B)
val onSecondaryContainerDark = Color(0xFF808080)
val tertiaryDark = Color(0xFF1B1B1B)
val onTertiaryDark = Color(0xFF1B1B1B)
val tertiaryContainerDark = Color(0xFF1B1B1B)
val onTertiaryContainerDark = Color(0xFF1B1B1B)
val backgroundDark = Color(0xFF3D3B38)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF1B1B1B)
val onSurfaceDark = Color(0xFF1B1B1B)
val surfaceVariantDark = Color(0xFF1B1B1B)
val onSurfaceVariantDark = Color(0xFF1B1B1B)
val surfaceTintDark = Color(0xFF1B1B1B)
val inverseSurfaceDark = Color(0xFF1B1B1B)
val inverseOnSurfaceDark = Color(0xFF1B1B1B)
val errorDark = Color(0xFF1B1B1B)
val onErrorDark = Color(0xFF1B1B1B)
val errorContainerDark = Color(0xFF1B1B1B)
val onErrorContainerDark = Color(0xFF1B1B1B)
val outlineDark = Color(0xFF1B1B1B)
val outlineVariantDark = Color(0xFF1B1B1B)
val scrimDark = Color(0xFF1B1B1B)

val primaryLight = Color(0xFFF0EBE4)
val onPrimaryLight = Color(0xFF000000)
val primaryContainerLight = Color(0xFFF0EBE4)
val onPrimaryContainerLight = Color(0xFF000000)
val inversePrimaryLight = Color(0xFF1B1B1B)
val secondaryLight = Color(0xFF1B1B1B)
val onSecondaryLight = Color(0xFF1B1B1B)
val secondaryContainerLight = Color(0xFFDDC9A6)
val onSecondaryContainerLight = Color(0xFF1B1B1B)
val tertiaryLight = Color(0xFF1B1B1B)
val onTertiaryLight = Color(0xFF1B1B1B)
val tertiaryContainerLight = Color(0xFF1B1B1B)
val onTertiaryContainerLight = Color(0xFF1B1B1B)
val backgroundLight = Color(0xFFBFAD8F)
val onBackgroundLight = Color(0xFFFFFFFF)
val surfaceLight = Color(0xFF1B1B1B)
val onSurfaceLight = Color(0xFF1B1B1B)
val surfaceVariantLight = Color(0xFF1B1B1B)
val onSurfaceVariantLight = Color(0xFF1B1B1B)
val surfaceTintLight = Color(0xFF1B1B1B)
val inverseSurfaceLight = Color(0xFF1B1B1B)
val inverseOnSurfaceLight = Color(0xFF1B1B1B)
val errorLight = Color(0xFF1B1B1B)
val onErrorLight = Color(0xFF1B1B1B)
val errorContainerLight = Color(0xFF1B1B1B)
val onErrorContainerLight = Color(0xFF1B1B1B)
val outlineLight = Color(0xFF1B1B1B)
val outlineVariantLight = Color(0xFF1B1B1B)
val scrimLight = Color(0xFF1B1B1B)